package com.learnsphere.ai.service;

import org.springframework.ai.chat.model.ChatModel;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Map;

@Service
public class AiDetectionService {

    private final ChatModel chatModel;

    @Autowired
    public AiDetectionService(ChatModel chatModel) {
        this.chatModel = chatModel;
    }

    public String detectAiContent(String text) {
        String promptTemplate = """
                Analyze the following text and determine the likelihood that it was generated by an AI (Artificial Intelligence) model.

                Text to Analyze:
                "{text}"

                Provide your analysis in the following JSON format:
                {lb}
                  "aiProbability": (integer between 0 and 100),
                  "analysis": "(brief explanation)",
                  "flags": ["(list of specific indicators found)"]
                {rb}
                """;

        // Truncate text if too long to fit context window (simplistic)
        String truncatedText = text.length() > 5000 ? text.substring(0, 5000) : text;

        PromptTemplate template = new PromptTemplate(promptTemplate);
        Prompt prompt = template.create(Map.of(
                "text", truncatedText,
                "lb", "{",
                "rb", "}"));

        String jsonResponse = chatModel.call(prompt).getResult().getOutput().getText();
        return jsonResponse;
    }
}
